name: CodeCov Upload

on:
  push:
    tags:
      - 'v*'

env:
  ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
jobs:
  cover:
    name: Coverrage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.18'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - run: go test -v -coverprofile=profile.cov ./...

      - uses: codecov/codecov-action@v2
        with:
          files: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos